/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Gmail & Calendar API
 * API pour intégrer Gmail et Google Calendar avec authentification OAuth2
 * OpenAPI spec version: 1.0.0
 */
export interface AuthResponse {
  /** URL d'autorisation Google */
  authUrl?: string;
  message?: string;
}

export interface TokenData {
  access_token?: string;
  refresh_token?: string;
  expiry_date?: number;
}

export interface Message {
  id?: string;
  threadId?: string;
  snippet?: string;
  subject?: string;
  from?: string;
  to?: string;
  date?: string;
}

export type CalendarEventStart = {
  dateTime?: string;
  date?: string;
};

export type CalendarEventEnd = {
  dateTime?: string;
  date?: string;
};

export interface CalendarEvent {
  id?: string;
  summary?: string;
  description?: string;
  start?: CalendarEventStart;
  end?: CalendarEventEnd;
}

export interface Error {
  error?: string;
  needsRefresh?: boolean;
}

export type GetAuthGoogleCallbackParams = {
  /**
   * Code d'autorisation retourné par Google
   */
  code: string;
  /**
   * Erreur éventuelle
   */
  error?: string;
};

export type GetAuthGoogleCallback200User = { [key: string]: unknown };

export type GetAuthGoogleCallback200 = {
  message?: string;
  userId?: string;
  user?: GetAuthGoogleCallback200User;
  tokens?: TokenData;
};

export type GetApiGmailUsersUserIdMessages200 = {
  messages?: Message[];
  total?: number;
};

export type GetApiCalendarEventsUserId200 = {
  events?: CalendarEvent[];
  total?: number;
};

export type PostAuthRefreshUserId200 = {
  message?: string;
  tokens?: TokenData;
};

export type GetAuthStatusUserId200 = {
  authenticated?: boolean;
  hasRefreshToken?: boolean;
  tokenExpired?: boolean;
  expiryDate?: string;
};

export type PostAuthLogoutUserId200 = {
  message?: string;
};
